import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Hero from "@/components/Hero";
import Navbar from "@/components/Navbar";
import Book from "@/components/Book";
import Intro from "@/components/Intro";
import Test from "@/components/Test";
import Sections from "@/components/Sections";
import PanoramaSlider from "@/components/PanoramaSlider";
import FreePanoramaSlider from "@/components/FreePanoramaSlider";
import SwiperPanoramaSlider from "@/components/SwiperPanoramaSlider";
import Sections2 from "@/components/Sections2";
import Sections3 from "@/components/Section3";
import Sections4 from "@/components/Section4";
import Sections5 from "@/components/Sections5";
import Footer from "@/components/Footer";
import Sections2Swiper from "@/components/Sections2Swiper";
// const inter = Inter({ su bsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} `}>
        <Navbar />
        <Hero />
        <Book />
        <Intro />
        <Sections />
        <Sections2 />
        <Sections3 />
        <Sections4 />
        <Sections5 />
        <Footer />
        {/* <SwiperPanoramaSlider /> */}
        {/* <PanoramaSlider /> */}
      </main>
    </>
  );
}
